USE baseball_db;

CREATE TABLE RH_prospect (
  player_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) DEFAULT NULL,
  last_name VARCHAR(100) DEFAULT NULL,
  team VARCHAR(100) DEFAULT NULL,
  age INT DEFAULT NULL,
  MLB INT DEFAULT NULL

);
  