DROP TABLE IF EXISTS RP_metric;

CREATE TABLE RP_metric (
  
  player_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) DEFAULT NULL,
  last_name VARCHAR(100) DEFAULT NULL,
  age INT DEFAULT NULL,
  xFIP DECIMAL(4,2) DEFAULT NULL,
  H9 DECIMAL(4,1) DEFAULT NULL,
  BB9 DECIMAL(4,1) DEFAULT NULL,
  K9 DECIMAL(4,1) DEFAULT NULL,
  HR9 DECIMAL(3,1) DEFAULT NULL,
  BB_p DECIMAL(3,1) DEFAULT NULL,
  K_p DECIMAL(3,1) DEFAULT NULL,
  KtoBB_p DECIMAL(3,1) DEFAULT NULL,
  BABIP DECIMAL(3,3) DEFAULT NULL,
  HRtoFB DECIMAL(3,1) DEFAULT NULL,
  GB_p DECIMAL(3,1) DEFAULT NULL,
  LOB_p DECIMAL(3,1) DEFAULT NULL,
  swing DECIMAL(3,1) DEFAULT NULL,
  barrel DECIMAL(3,1) DEFAULT NULL,
  HardHit DECIMAL(3,1) DEFAULT NULL,
  FB_spin INT DEFAULT NULL,
  CB_spin INT DEFAULT NULL
  
);
  