INSERT INTO outfield (
    player_id,first_name,last_name,team,age
)

VALUES 

(1,'Mitch','Haniger','Seattle',30),
(2,'Cedric','Mullins','Baltimore',26),
(3,'Robbie','Grossman','Detroit',31),
(4,'Juan','Soto','Washington',22),
(5,'Bryan','Reynolds','Pittsburgh',26),
(6,'Myles','Straw','Cleveland',26),
(7,'JD','Martinez','Boston',33),
(8,'Aaron','Judge','New York(A)',29),
(9,'Mark','Canha','Oakland',32),
(10,'Adolis','Garcia','Texas',28),
(11,'Dylan','Carlson','St.Louis',22),
(12,'Joey','Gallo','New York(A)',27),
(13,'Randy','Arozarena','Tampa Bay',26),
(14,'Alex','Verdugo','Boston',25),
(15,'Jorge','Soler','Atlanta',29),
(16,'Bryce','Harper','Philadelphia',28),
(17,'Yordan','Alvarez','Houston',24),
(18,'Teoscar','Hernandez','Toronto',28),
(19,'Austin','Meadows','Tampa Bay',26),
(20,'Nick','Castellanos','Cincinnati',29),
(21,'Charlie','Blackmon','Colorado',34),
(22,'Andrew','McCutchen','Philadelphia',34),
(23,'Hunter','Renfroe','Milwaukee',29),
(24,'Kyle','Tucker','Houston',24),
(25,'Tommy','Pham','San Diego',33),
(26,'Adam','Duvall','Atlanta',32),
(27,'Mookie','Betts','Los Angeles(N)',28),
(28,'Randal','Grichuk','Toronto',29),
(29,'Lourdes','Gurriel','Toronto',27),
(30,'Andrew','Benintendi','Kansas City',26),
(31,'David','Peralta','Arizona',33),
(32,'Tyler','ONeill','St.Louis',26),
(33,'Ian','Happ','Chicago(N)',26),
(34,'Raimel','Tapia','Colorado',27),
(35,'Mike','Yastrzemski','San Francisco',30),
(36,'Austin','Hays','Baltimore',25),
(37,'Michael A.','Taylor','Kansas City',30),
(38,'Trent','Grisham','San Diego',24),
(39,'Starling','Marte','New York(N)',32),
(40,'Avisail','Garcia','Miami',30),
(41,'Michael','Brantley','Houston',34),
(42,'Wil','Myers','San Diego',30),
(43,'Dominic','Smith','New York(N)',26),
(44,'Odubel','Herrera','Philadelphia',29),
(45,'Max','Kepler','Minnesota',28),
(46,'Jesse','Winker','Cincinnati',27),
(47,'Joc','Pederson','Atlanta',29),
(48,'Michael','Conforto','New York(N)',28),
(49,'Christian','Yelich','Milwaukee',29),
(50,'Leury','Garcia','Chicago(A)',30),
(51,'Kyle','Schwarber','Boston',28),
(52,'Andrew','Vaughn','Chicago(A)',23),
(53,'Manuel','Margot','Tampa Bay',26),
(54,'Akil','Baddoo','Detroit',22),
(55,'Brett','Gardner','New York(A)',37),
(56,'Tyler','Naquin','Cincinnati',30),
(57,'Anthony','Santander','Baltimore',26),
(58,'Jackie','Bradley Jr','Boston',31),
(59,'AJ','Pollack','Los Angeles(N)',33),
(60,'Eddie','Rosario','Atlanta',29),
(61,'Jurickson','Profar','San Diego',28),
(62,'Harrison','Bader','St.Louis',27),
(63,'Ben','Gamel','Pittsburgh',29),
(64,'Kevin','Kiermaier','Tampa Bay',31),
(65,'Brandon','Nimmo','New York(N)',28),
(66,'Gregory','Polanco','Pittsburgh',29),
(67,'LaMonte','Wade','San Francisco',27),
(68,'Ramon','Laureano','Oakland',26),
(69,'Jarred','Kelenic','Seattle',21),
(70,'Ketel','Marte','Arizona',27),
(71,'Victor','Robles','Washington',24),
(72,'Corey','Dickerson','Baltimore',32),
(73,'Justin','Upton','Los Angeles(A)',33),
(74,'Harold','Ramirez','Cleveland',26),
(75,'Ronald','Acuna','Atlanta',23),
(76,'Jason','Heyward','Chicago(N)',31),
(77,'Cody','Bellinger','Los Angeles(N)',25),
(78,'Bradley','Zimmer','Cleveland',28),
(79,'George','Springer','Toronto',31),
(80,'Yonathan','Daza','Colorado',27),
(81,'Rafael','Ortega','Chicago(N)',30),
(82,'Chas','McCormick','Houston',26),
(83,'DJ','Stewart','Baltimore',27),
(84,'Seth','Brown','Oakland',28),
(85,'Austin','Slater','San Francisco',28),
(86,'Trevor','Larnach','Minnesota',24),
(87,'Luis','Robert','Chicago(A)',23),
(88,'Yadiel','Hernandez','Washington',33),
(89,'Lorenzon','Cain','Milwaukee',35),
(90,'Willie','Calhoun','Texas',26),
(91,'Tyrone','Taylor','Milwaukee',27),
(92,'Jake','Fraley','Seattle',26),
(93,'Brandon','Marsh','Los Angeles(A)',23),
(94,'Byron','Buxton','Minnesota',27),
(95,'Jesus','Sanchez','Miami',23),
(96,'Josh','Naylor','Cleveland',24),
(97,'Sam','Hilliard','Colorado',27),
(98,'Oscar','Mercado','Cleveland',26),
(99,'Eloy','Jimenez','Chicago(A)',24),
(100,'Alex','Kirilloff','Minnesota',23),
(101,'David','Dahl','Texas',27),
(102,'Bryan','De La Cruz','Miami',24),
(103,'Clint','Frazier','Chicago(N)',26),
(104,'Nick','Gordon','Minnesota',25),
(105,'Marcell','Ozuna','Atlanta',30),
(106,'Aristides','Aquino','Cincinnati',27),
(107,'Leody','Taveras','Texas',22),
(108,'Taylor','Trammell','Seattle',23),
(109,'Miguel','Andujar','New York(A)',26),
(110,'Kyle','Lewis','Seattle',25),
(111,'Mike','Trout','Los Angeles(A)',29),
(112,'Jo','Adell','Los Angeles(A)',22),
(113,'Nick','Senzel','Cincinnati',26),
(114,'Daz','Cameron','Detroit',24),
(115,'Jarren','Duran','Boston',24),
(116,'Edward','Olivares','Kansas City',25);

SELECT * FROM outfield;
